# Generated by Django 5.2.7 on 2025-10-06 11:51

import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for UI', max_length=7)),
                ('icon', models.CharField(default='fas fa-folder', help_text='Font Awesome icon class', max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Marube Snipher Abel', max_length=100)),
                ('site_description', models.TextField(blank=True)),
                ('admin_email', models.EmailField(default='hello@marube.dev', max_length=254)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('dev_to_url', models.URLField(blank=True)),
                ('coffee_enabled', models.BooleanField(default=True)),
                ('default_coffee_amount', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('website', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Database'), ('devops', 'DevOps'), ('tool', 'Tool')], default='tool', max_length=50)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoffeePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(blank=True, help_text='Customer name (optional)', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Customer email (optional)', max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in USD', max_digits=8, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('KES', 'KES')], default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('card', 'Credit Card'), ('bank', 'Bank Transfer')], default='mpesa', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=100)),
                ('mpesa_code', models.CharField(blank=True, help_text='M-Pesa transaction code', max_length=20, verbose_name='M-Pesa Code')),
                ('is_paid', models.BooleanField(default=False, help_text='Payment has been successfully processed')),
                ('paid_at', models.DateTimeField(blank=True, help_text='When the payment was completed', null=True)),
                ('message', models.TextField(blank=True, help_text='Optional message from the supporter')),
                ('public_message', models.BooleanField(default=False, help_text='Display this message publicly (if provided)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Customer IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Customer browser user agent')),
            ],
            options={
                'verbose_name': 'Coffee Purchase',
                'verbose_name_plural': 'Coffee Purchases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_status', 'is_paid'], name='main_coffee_payment_e605a7_idx'), models.Index(fields=['created_at'], name='main_coffee_created_9a0940_idx'), models.Index(fields=['transaction_id'], name='main_coffee_transac_5ef2b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(help_text='Project title (max 200 characters)', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Detailed project description')),
                ('short_description', models.CharField(help_text='Brief description for project cards (max 300 characters)', max_length=300)),
                ('image', models.ImageField(blank=True, help_text='Project thumbnail image (recommended: 800x600px)', null=True, upload_to='projects/%Y/%m/')),
                ('featured_image', models.ImageField(blank=True, help_text='Featured project image for highlights', null=True, upload_to='projects/featured/%Y/%m/')),
                ('project_type', models.CharField(choices=[('web_app', 'Web Application'), ('mobile_app', 'Mobile Application'), ('desktop_app', 'Desktop Application'), ('api', 'API Service'), ('library', 'Library/Tool'), ('other', 'Other')], default='web_app', max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('planned', 'Planned'), ('archived', 'Archived')], default='completed', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Feature this project on the homepage')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which projects are displayed (lower numbers first)')),
                ('project_url', models.URLField(blank=True, help_text='Link to live project demo', null=True, verbose_name='Live Demo URL')),
                ('github_url', models.URLField(blank=True, help_text='Link to source code repository', null=True, verbose_name='GitHub Repository')),
                ('documentation_url', models.URLField(blank=True, help_text='Link to project documentation', null=True)),
                ('start_date', models.DateField(blank=True, help_text='Project start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Project completion date', null=True)),
                ('client', models.CharField(blank=True, help_text='Client name (if applicable)', max_length=200)),
                ('categories', models.ManyToManyField(blank=True, related_name='projects', to='main.category')),
                ('technologies', models.ManyToManyField(blank=True, help_text='Technologies used in this project', related_name='projects', to='main.technology')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(help_text='Blog post title (max 200 characters)', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', max_length=200, unique=True)),
                ('content', tinymce.models.HTMLField(help_text='Main content of the blog post')),
                ('excerpt', models.TextField(help_text='Brief excerpt for post preview (max 500 characters)', max_length=500)),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the blog post (recommended: 1200x630px)', null=True, upload_to='blog/%Y/%m/')),
                ('image_alt', models.CharField(blank=True, help_text='Alt text for the featured image', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('post_type', models.CharField(choices=[('tutorial', 'Tutorial'), ('article', 'Article'), ('news', 'News'), ('review', 'Review'), ('case_study', 'Case Study')], default='article', max_length=20)),
                ('published', models.BooleanField(default=False, help_text='Make this post publicly visible')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Date and time when the post was published', null=True)),
                ('featured', models.BooleanField(default=False, help_text='Feature this post on the homepage')),
                ('meta_description', models.CharField(blank=True, help_text='Meta description for SEO', max_length=300)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=200)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this post has been viewed')),
                ('reading_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='blog_posts', to='main.category')),
                ('related_projects', models.ManyToManyField(blank=True, help_text='Projects related to this post', related_name='blog_posts', to='main.project')),
                ('tags', models.ManyToManyField(blank=True, related_name='blog_posts', to='main.tag')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['published', 'status'], name='main_blogpo_publish_30fd94_idx'), models.Index(fields=['published_at'], name='main_blogpo_publish_efb0d4_idx'), models.Index(fields=['slug'], name='main_blogpo_slug_b48d6a_idx'), models.Index(fields=['featured'], name='main_blogpo_feature_cefb6d_idx')],
                'constraints': [models.UniqueConstraint(fields=('slug', 'published_at'), name='unique_slug_published_date')],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['featured', 'status'], name='main_projec_feature_5f1a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='main_projec_created_0bbe51_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='main_projec_slug_96fae4_idx'),
        ),
    ]
