# Generated by Django 5.2.7 on 2025-10-05 12:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for UI', max_length=7)),
                ('icon', models.CharField(default='fas fa-folder', help_text='Font Awesome icon class', max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Marube Snipher Abel', max_length=100)),
                ('site_description', models.TextField(blank=True)),
                ('admin_email', models.EmailField(default='hello@marube.dev', max_length=254)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('dev_to_url', models.URLField(blank=True)),
                ('coffee_enabled', models.BooleanField(default=True)),
                ('default_coffee_amount', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('website', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Database'), ('devops', 'DevOps'), ('tool', 'Tool')], default='tool', max_length=50)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='coffeepurchase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Coffee Purchase', 'verbose_name_plural': 'Coffee Purchases'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(default=False, help_text='Feature this post on the homepage'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the featured image', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Meta description for SEO', max_length=300),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_type',
            field=models.CharField(choices=[('tutorial', 'Tutorial'), ('article', 'Article'), ('news', 'News'), ('review', 'Review'), ('case_study', 'Case Study')], default='article', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reading_time',
            field=models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_projects',
            field=models.ManyToManyField(blank=True, help_text='Projects related to this post', related_name='blog_posts', to='main.project'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this post has been viewed'),
        ),
        migrations.AddField(
            model_name='coffeepurchase',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('KES', 'KES')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='coffeepurchase',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Customer IP address', null=True),
        ),
        migrations.AddField(
            model_name='coffeepurchase',
            name='mpesa_code',
            field=models.CharField(blank=True, help_text='M-Pesa transaction code', max_length=20, verbose_name='M-Pesa Code'),
        ),
        migrations.AddField(
            model_name='coffeepurchase',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When the payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='coffeepurchase',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('card', 'Credit Card'), ('bank', 'Bank Transfer')], default='mpesa', max_length=20),
        ),
        migrations.AddField(
            model_name='coffeepurchase',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='coffeepurchase',
            name='public_message',
            field=models.BooleanField(default=False, help_text='Display this message publicly (if provided)'),
        ),
        migrations.AddField(
            model_name='coffeepurchase',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=100),
        ),
        migrations.AddField(
            model_name='coffeepurchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='coffeepurchase',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Customer browser user agent'),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, help_text='Client name (if applicable)', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which projects are displayed (lower numbers first)'),
        ),
        migrations.AddField(
            model_name='project',
            name='documentation_url',
            field=models.URLField(blank=True, help_text='Link to project documentation', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Project completion date', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured project image for highlights', null=True, upload_to='projects/featured/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('web_app', 'Web Application'), ('mobile_app', 'Mobile Application'), ('desktop_app', 'Desktop Application'), ('api', 'API Service'), ('library', 'Library/Tool'), ('other', 'Other')], default='web_app', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(default=1, help_text='Brief description for project cards (max 300 characters)', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=1, help_text='URL-friendly version of the title', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='Project start date', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('planned', 'Planned'), ('archived', 'Archived')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Main content of the blog post'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(help_text='Brief excerpt for post preview (max 500 characters)', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for the blog post (recommended: 1200x630px)', null=True, upload_to='blog/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=False, help_text='Make this post publicly visible'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date and time when the post was published', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of the title', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='Blog post title (max 200 characters)', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='coffeepurchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in USD', max_digits=8, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='coffeepurchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='coffeepurchase',
            name='email',
            field=models.EmailField(blank=True, help_text='Customer email (optional)', max_length=254),
        ),
        migrations.AlterField(
            model_name='coffeepurchase',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Payment has been successfully processed'),
        ),
        migrations.AlterField(
            model_name='coffeepurchase',
            name='message',
            field=models.TextField(blank=True, help_text='Optional message from the supporter'),
        ),
        migrations.AlterField(
            model_name='coffeepurchase',
            name='name',
            field=models.CharField(blank=True, help_text='Customer name (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Detailed project description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='Feature this project on the homepage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='Link to source code repository', null=True, verbose_name='GitHub Repository'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Project thumbnail image (recommended: 800x600px)', null=True, upload_to='projects/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, help_text='Link to live project demo', null=True, verbose_name='Live Demo URL'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Project title (max 200 characters)', max_length=200),
        ),
        migrations.AddIndex(
            model_name='coffeepurchase',
            index=models.Index(fields=['payment_status', 'is_paid'], name='main_coffee_payment_e605a7_idx'),
        ),
        migrations.AddIndex(
            model_name='coffeepurchase',
            index=models.Index(fields=['created_at'], name='main_coffee_created_9a0940_idx'),
        ),
        migrations.AddIndex(
            model_name='coffeepurchase',
            index=models.Index(fields=['transaction_id'], name='main_coffee_transac_5ef2b3_idx'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='main.category'),
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='projects', to='main.category'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='main.tag'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['published', 'status'], name='main_blogpo_publish_30fd94_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['published_at'], name='main_blogpo_publish_efb0d4_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='main_blogpo_slug_b48d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['featured'], name='main_blogpo_feature_cefb6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='blogpost',
            constraint=models.UniqueConstraint(fields=('slug', 'published_at'), name='unique_slug_published_date'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['featured', 'status'], name='main_projec_feature_5f1a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='main_projec_created_0bbe51_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='main_projec_slug_96fae4_idx'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, help_text='Technologies used in this project', related_name='projects', to='main.technology'),
        ),
    ]
