"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v@!2!hv_j9o8hiosua!bb)-9ah5(%-wwms$ix1w8iq%1b)l@+7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = ['https://e801e135d399.ngrok-free.app']
TRUSTED_HOSTS = ['*']  # For development purposes, allow all hosts



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_ROOT = BASE_DIR / 'static/media'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Admin interface improvements
ADMIN_SITE_HEADER = "Marube Snipher Abel Portfolio Admin"
ADMIN_SITE_TITLE = "Portfolio Administration"
ADMIN_INDEX_TITLE = "Dashboard"

# File upload settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB


# settings.py
TINYMCE_DEFAULT_CONFIG = {
    'height': 600,
    'width': '100%',
    'menubar': 'file edit view insert format tools table help',
    'plugins': '''
        advlist autolink lists link image charmap print preview anchor
        searchreplace visualblocks code codesample fullscreen
        insertdatetime media table paste code help wordcount
        emoticons
    ''',
    'toolbar': '''
        undo redo | formatselect | bold italic underline forecolor backcolor |
        alignleft aligncenter alignright alignjustify |
        bullist numlist outdent indent | link image media |
        codesample code | table | emoticons | fullscreen preview
    ''',
    'toolbar_mode': 'floating',
    'codesample_languages': [
        {'text': 'Python', 'value': 'python'},
        {'text': 'JavaScript', 'value': 'javascript'},
        {'text': 'HTML/XML', 'value': 'markup'},
        {'text': 'CSS', 'value': 'css'},
        {'text': 'Django Template', 'value': 'django'},
        {'text': 'SQL', 'value': 'sql'},
        {'text': 'Bash/Shell', 'value': 'bash'},
        {'text': 'JSON', 'value': 'json'},
        {'text': 'YAML', 'value': 'yaml'},
        {'text': 'Git', 'value': 'git'},
        {'text': 'Docker', 'value': 'docker'},
        {'text': 'Nginx', 'value': 'nginx'},
        {'text': 'Markdown', 'value': 'markdown'},
        {'text': 'Plain Text', 'value': 'text'},
    ],
    'codesample_dialog_width': 600,
    'codesample_dialog_height': 400,
    'content_style': '''
        body { 
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; 
            font-size: 14px; 
            line-height: 1.6;
        }
        pre {
            background: #f8f9fa;
            border: 1px solid #e9ecef;
            border-radius: 8px;
            padding: 1.5rem;
            overflow-x: auto;
            position: relative;
            margin: 1.5rem 0;
        }
        code {
            background: #f1f3f4;
            padding: 0.2rem 0.4rem;
            border-radius: 4px;
            color: #d73a49;
            font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
            font-size: 0.9em;
        }
        pre code {
            background: transparent;
            padding: 0;
            color: inherit;
            border-radius: 0;
        }
    ''',
    'paste_data_images': True,
    'image_advtab': True,
    'link_list': [
        {'title': 'Home', 'value': '/'},
        {'title': 'Blog', 'value': '/blog/'},
    ],
}